version: '2'

services:

  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: 'developmentseed/geolambda:base'
    entrypoint: /bin/bash

  core:
    build:
      context: .
    image: 'developmentseed/geolambda:core'
    entrypoint: /bin/bash
    links:
      - base

  min:
    build:
      context: .
      dockerfile: Dockerfile.min
    image: 'developmentseed/geolambda:min'
    entrypoint: /bin/bash
    links:
      - core

  full:
    build:
      context: .
      dockerfile: Dockerfile.full
    image: 'developmentseed/geolambda:full'
    entrypoint: /bin/bash
    links:
      - core
